version: "3.9"

services:
  backend:
    container_name: backend
    build: 
      context: backend
      dockerfile: Dockerfile
    image: backend-dev
    ports:
      - 4000:3000
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - db

  frontend:
    container_name: frontend
    build: 
      context: frontend
      dockerfile: Dockerfile
    image: frontend-dev
    ports:
      - 8080:80
    networks:
      - frontend

  db:
    container_name: postgres
    image: postgres
    env_file: .env
    restart: always
    networks:
      - backend
    volumes:
      - postgres_data:/data/postgres

  # adminer:
  #   container_name: adminer
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8081:8080
    # networks:
    #   - backend

networks:
  backend:
  frontend:

volumes: 
  postgres_data: